source 'https://rubygems.org'

gem 'rspec'
gem 'appium_lib', '~> 9.4'
gem 'require_all'
gem 'parallel_split_test'
gem 'sauce_whisk', '>= 0.0.22'
gem 'rake'
gem 'selenium-webdriver', '~> 3.0'
gem 'rest-client'
